# Generated by Django 2.2.8 on 2019-12-14 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 12, 19, 30, 886585)),
        ),
    ]
